# Generated by Django 3.2 on 2021-05-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersurl",
            options={"verbose_name_plural": "usersurls"},
        ),
    ]
