# Generated by Django 3.2.3 on 2021-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0008_auto_20210510_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersurl",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usersurl",
            name="short",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="usersurl",
            name="url",
            field=models.CharField(max_length=50),
        ),
    ]
