# Generated by Django 3.2.3 on 2021-05-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_auto_20210517_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurl',
            name='url_content',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersurl',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
