# Generated by Django 3.2.3 on 2021-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0012_alter_usersurl_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersurl",
            name="url_content",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
