# Generated by Django 3.2.3 on 2021-06-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_alter_usersurl_url_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurl',
            name='url_content',
            field=models.TextField(max_length=500),
        ),
    ]
